version: '3'
services:
  docker:
    container_name: docker
    image: m.daocloud.io/docker.io/library/registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./data:/var/lib/registry
      - ./docker/config.yml:/etc/docker/registry/config.yml
  nvcr:
    container_name: nvcr
    image: m.daocloud.io/docker.io/library/registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./data:/var/lib/registry
      - ./nvcr/config.yml:/etc/docker/registry/config.yml
  gcr:
    container_name: gcr
    image: m.daocloud.io/docker.io/library/registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./data:/var/lib/registry
      - ./gcr/config.yml:/etc/docker/registry/config.yml
  ghcr:
    container_name: ghcr
    image: m.daocloud.io/docker.io/library/registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./data:/var/lib/registry
      - ./ghcr/config.yml:/etc/docker/registry/config.yml
  k8s:
    container_name: k8s
    image: m.daocloud.io/docker.io/library/registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./data:/var/lib/registry
      - ./k8s/config.yml:/etc/docker/registry/config.yml
  quay:
    container_name: quay
    image: m.daocloud.io/docker.io/library/registry:2.8.3
    restart: always
    environment:
      - HTTP_PROXY=${PROXY}
      - HTTPS_PROXY=${PROXY}
    volumes:
      - ./data:/var/lib/registry
      - ./quay/config.yml:/etc/docker/registry/config.yml
  custom:
    container_name: custom 
    image: m.daocloud.io/docker.io/library/registry:2.8.3
    restart: always
    volumes:
      - ./data:/var/lib/registry
      - ./custom/config.yml:/etc/docker/registry/config.yml
  nginx:
    container_name: nginx
    image: m.daocloud.io/docker.io/library/nginx:alpine
    restart: always
    ports:
        - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./cert:/etc/nginx/cert
